#!/usr/bin/env python3
"""Fit the FIXED tables used by the C++ gaze engine to predict an ongoing saccade (set A of datasets 1+2, 1 kHz, human labels only for the fit).

At time tau (ms) after the onset, with  d = distance moved since the onset,  v = current speed (deg/ms, mean of the last 3 samples),
vmax = peak speed so far, all along the current direction u, the displacement still to come over the next h ms (h = until the end / 10 / 20) is
    r_h = a_h(tau) * d + b_h(tau) * v + c_h(tau) * vmax          (ridge regression per 2 ms bin of tau)
and the Laplace scale of the residual is stored as the uncertainty. Output: cpp/include/uneye/gaze_tables.hpp
"""
import os, sys
import numpy as np
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
sys.path.insert(0, os.path.join(root, "online"))
import experiment as E, forecast as Fc

NB, BIN = 30, 2.0          # 30 bins of 2 ms: tau 0..60 ms (the last bin is used for everything later)
HS = (None, 10, 20)         # None = until the end of the saccade

d = E.Data(sets=("1", "2"), n_test=10)
rows = []
for s in ("1", "2"):
    V, L, fs = d.tr[s]; X, Y = d.raw[s][:2]
    art = Fc.artifact_mask(X, Y, fs)
    for i in range(X.shape[0]):
        dd = np.diff(np.r_[0, (L[i] > 0).astype(int), 0])
        for on, off in zip(np.where(dd == 1)[0], np.where(dd == -1)[0] - 1):
            if on < 1 or off - on < 3 or art[i, max(on - 5, 0):off + 25].any() or off + 21 >= X.shape[1]: continue
            p0 = np.array([X[i, on - 1], Y[i, on - 1]]); vmax = 0.0
            for t in range(on, off + 1):
                p = np.array([X[i, t], Y[i, t]]); disp = p - p0; dist = np.linalg.norm(disp)
                v = np.linalg.norm(V[i, :, max(t - 2, 0):t + 1].mean(1)) * fs / 1000.0
                vmax = max(vmax, v)
                u = disp / dist if dist > 1e-6 else np.array([1.0, 0.0])
                tgt = []
                for h in HS:
                    q = np.array([X[i, off], Y[i, off]]) if h is None else np.array([X[i, min(t + h, off + 20)], Y[i, min(t + h, off + 20)]])
                    tgt.append(float((q - p) @ u))
                rows.append((min((t - on) * 1000.0 / fs, NB * BIN - 1e-6), dist, v, vmax, *tgt))
R = np.array(rows); print("training samples:", len(R))
coef = np.zeros((len(HS), NB, 3)); scale = np.zeros((len(HS), NB))
for b in range(NB):
    m = (R[:, 0] >= b * BIN) & (R[:, 0] < (b + 1) * BIN)
    F = R[m, 1:4]
    for k in range(len(HS)):
        y = R[m, 4 + k]
        w = np.linalg.solve(F.T @ F + 1e-3 * np.eye(3), F.T @ y)
        res = y - F @ w
        coef[k, b], scale[k, b] = w, max(np.median(np.abs(res)) / np.log(2), 1e-3)
out = os.path.join(root, "cpp", "include", "uneye", "gaze_tables.hpp")
with open(out, "w") as f:
    f.write("// GENERATED by cpp/scripts/fit_landing_tables.py from set A of datasets 1+2 (1 kHz). Do not edit by hand.\n#pragma once\n\nnamespace uneye { namespace gaze {\n")
    f.write(f"constexpr int kLandBins = {NB};\nconstexpr double kLandBinMs = {BIN};\nconstexpr int kLandTargets = {len(HS)};   // 0: until the end of the saccade, 1: +10 ms, 2: +20 ms\n")
    f.write("// remaining displacement along the current direction = a*d + b*v + c*vmax   (d in deg, v and vmax in deg/ms)\n")
    f.write("constexpr double kLandCoef[kLandTargets][kLandBins][3] = {\n")
    for k in range(len(HS)):
        f.write("  {\n" + ",\n".join("    {%.6g, %.6g, %.6g}" % tuple(coef[k, b]) for b in range(NB)) + "\n  },\n")
    f.write("};\n// Laplace scale (deg) of the residual\nconstexpr double kLandScale[kLandTargets][kLandBins] = {\n")
    for k in range(len(HS)):
        f.write("  {" + ", ".join("%.5g" % scale[k, b] for b in range(NB)) + "},\n")
    f.write("};\n}}  // namespace uneye::gaze\n")
print("written", out)
